language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: quidam74-github
# command to run tests
script:
  - pytest -v --cov .
  - sonar-scanner
  #- coveralls
branches:
  only:
  - master
  - feaure/fbellanger